libsandbox/trace.c: tweak ptrace command type for musl
glibc defines ptrace as:
  long ptrace(enum __ptrace_request request, pid_t pid, void *addr, void *data);
musl defines ptrace as:
  long ptrace(int, ...);

This causes build failure in for of:
    ../../sandbox-2.17/libsandbox/trace/linux/x86_64.c: In function 'trace_set_ret':
    ../../sandbox-2.17/libsandbox/trace/linux/x86_64.c:99:2: error: type of formal parameter 1 is incomplete
      trace_set_regs(regs);
      ^~~~~~~~~~~~~~

Let's clobber to 'int' lowest common denominator.

Bug: https://bugs.gentoo.org/549108
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>